#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "nocodb"
name = "NocoDB"
description.en = "No-code platform that turns any database into a smart spreadsheet"
description.fr = "Plateform sans code qui transforme toute base de données en un tableur intelligent"

version = "2026.06.1~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "AGPL-3.0-only"
website = "https://www.nocodb.com"
demo = "https://www.nocodb.com/demos"
code = "https://github.com/nocodb/nocodb"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "450M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.en = "The app has its own user login system, so you can disable YunoHost's SSO, especially if you use NocoDB's API."
    help.fr = "L'application a son propre système d'authentification, vous pouvez donc désactiver le SSO de YunoHost, particulièrement si vous utilisez l'API de NocoDB."
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/nocodb/nocodb/archive/refs/tags/2026.08.0.tar.gz"
    sha256 = "ffe59b5ae866c85c1446753ec5031eb3bbbb85ed28661b4c70c666794dfdec60"
    autoupdate.strategy = "latest_github_release"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = [
        "postgresql",
        "redis-server"
    ]

    [resources.nodejs]
    version = "24.14.0"

    [resources.database]
    type = "postgresql"
