#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # -------------------------------
    # Curl tests to validate that the app works
    # -------------------------------
    [default.curl_tests]
    home.path = "/dashboard/#/signup"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.e6e2d1ca0d5f38a4052c98d5990a26fcbfd1d452.name = "Upgrade from 0.202.4~ynh1"
